spring:
  application:
    name: JatiStore
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    # Default fallback (overridden by application-dev.yaml)
    url: jdbc:postgresql://localhost:5432/jatistore?stringtype=unspecified
    username: developer
    password: rahasia
  jpa:
    hibernate:
      # Tell Hibernate to only validate the schema, leaving structural changes strictly to Flyway
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  flyway:
    # Enable Flyway database migrations
    enabled: true
    baseline-on-migrate: true
jwt:
  secret: ${JWT_SECRET:9aDf784GjkLpQweRtyUioPasDfgHjKlZxcVbnM1234567890QWERTYUIOPASDFGHJKLZXCVBNM_HS512_VERY_SECRET_AND_LONG_KEY}
  expiration-seconds:
    admin: 360000
    seller: 360000
    user: 360000

allowed:
  origins: ${ALLOWED_ORIGINS:http://localhost:5173}

cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://653729848272621:_oe0o7FhXU_9-GDZi_Q2En2zJDA@dqoqfiucw}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha