spring:
  application:
    name: JatiStore
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    # Default fallback (overridden by application-dev.yaml)
    url: jdbc:postgresql://localhost:5432/jatistore
    username: developer
    password: rahasia
  jpa:
    hibernate:
      # Tell Hibernate to only validate the schema, leaving structural changes strictly to Flyway
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    # Enable Flyway database migrations
    enabled: true
    baseline-on-migrate: true

